#!/bin/bash

ANS=`echo "$0" | sed "s/\(.*\)c/\1o/"`
RCANS=`echo "$0" | sed "s/\(.*\)c/\1o/"`_rc
OUT=out/`echo "$0" | sed "s/\(.*\)c/\1o/" | sed "s/\.\/cases\///" | sed "s/\//_/"`
RCOUT=out/`echo "$0" | sed "s/\(.*\)c/\1o/" | sed "s/\.\/cases\///" | sed "s/\//_/"`_rc
FN=`basename $0`

sudo rm -f $RCOUT

dd if=/dev/zero of=disks/${FN}.disk bs=64M count=1 &> /dev/null                
mkfs.vfat -I -F 32 -f 1 -S 512 -s 1 -R 32 disks/${FN}.disk &> /dev/null
sudo mount disks/${FN}.disk mnt
sudo dd if=/dev/zero of=mnt/TEST bs=512 count=1 &> /dev/null
sync -f
sudo touch mnt/TEST1
sudo rm mnt/TEST
sudo umount mnt
sudo mount disks/${FN}.disk mnt
sync -f
sudo dd conv=notrunc,noerror,fdatasync if=/dev/zero of=mnt/TEST1 bs=66571776 count=1 &> /dev/null
sudo umount mnt

./recover -d disks/${FN}.disk -r TEST -o $RCOUT 1>$OUT
ret=0
diff -w $ANS $OUT
ret=$(($?|$ret))
test -e $RCOUT
ret=$((!$?|$ret))
exit $ret
