#!/bin/bash

ANS=`echo "$0" | sed "s/\(.*\)c/\1o/"`
OUT=out/`echo "$0" | sed "s/\(.*\)c/\1o/" | sed "s/\.\/cases\///" | sed "s/\//_/"`
FN=`basename $0`

dd if=/dev/zero of=disks/${FN}.disk bs=32M count=1 &> /dev/null                
mkfs.vfat -I -F 32 -f 2 -S 512 -s 1 -R 2 disks/${FN}.disk &> /dev/null        
sudo mount disks/${FN}.disk mnt
sudo cp utils/sfile mnt/longfilename
for i in {1..3}
do
    sudo cp utils/sfile mnt/$i.TXT
done
sync -f
sudo umount mnt

./recover -d disks/${FN}.disk -l  1>$OUT
diff -w $ANS $OUT
exit $?
