#M1#

ds=(
"M1-1: ./recover"
"M1-2: ./recover 123"
"M1-3: ./recover -l /DUMMY"
"M1-4: ./recover -d disks/dummy.disk -l /"
"M1-5: ./recover -d disks/dummy.disk -r TARGET"
"M1-6: ./recover -d disks/dummy.disk -r TARGET -o"
"M1-7: ./recover -r TARGET -o dest"
"M1-8: ./recover -l / -d dummy.disk"
"M1-9: ./recovery -l / -d dummy.disk"
"M1-10: ./recover -d \`perl -e 'print \"A\"x10240'\` -l /DUMMY -r a"
"M1-11: ./recover -d dummy.disk -x"
"M2-1: mkfs.vfat -I -F 32 disks/${FN}.disk &> /dev/null"
"M2-2: mkfs.vfat -I -F 32 -f 1 disks/${FN}.disk &> /dev/null"
"M2-3: mkfs.vfat -I -F 32 -f 1 -S 512 disks/${FN}.disk &> /dev/null"
"M2-4: mkfs.vfat -I -F 32 -f 1 -S 512 -s 4 disks/${FN}.disk &> /dev/null"
"M2-5: mkfs.vfat -I -F 32 -f 1 -S 512 -s 2 -R 64 disks/${FN}.disk &> /dev/null"
"M2-6: mkfs.vfat -I -F 32 -f 4 -S 512 -s 1 -R 32 disks/${FN}.disk &> /dev/null"
"M2-7: dd if=/dev/zero of=disks/${FN}.disk bs=128M count=1 &> /dev/null"
"M3-1: List a file with extension."
"M3-2: List three file."
"M3-3: List a file without extension."
"M3-4: List a 8.3 file with 11 characters."
"M3-5: List 17 files in two clusters."
"M3-6: List three files in 2 FATs."
"M3-7: List 33 files in -S 1024."
"M3-8: List 33 files in -s 2."
"M3-9: List 33 files in -R 2."
"M3-10: List 3 files in 30M disk size."
"M3-11: List files with LFN."
"M3-12: List files with directory."
"M3-13: List files with directory and extension."
"M3-14: List deleted files."
"M3-15: List disk with deleted files and new added files."
"M3-16: List deleted directory."
"M4-1: file not found."
"M4-2: Recover one single file."
"M4-3: Reocvered file located after three files."
"M4-4: Reocvered file located in the second cluster of root entry."
"M4-5: Reocvered file located in the middle of root entry."
"M4-6: Reocvered file located in the middle of root entry, other file are deleted."
"M4-7: Reocver an empty file.."
"M4-8: error - fail to recover"
"M4-9: fail to open"
"M4-10: Recover file in FAT high address"
"M4-11: Recover file with 0x00 in the begining."
"M5-1: file not found."
"M5-2: Cleanse one single file."
"M5-3: Cleansed file located after three files."
"M5-4: Cleanse file located in the second cluster of root entry."
"M5-5: Cleanse file located in the middle of root entry."
"M5-6: Cleanse file located in the middle of root entry, other file are deleted."
"M5-7: Cleanse an empty file.."
"M5-8: error - fail to cleanse"
"M5-9: Cleanse file in FAT high address"
"M5-10: Cleanse file with 0x00 in the begining."
)

